CREATE TABLE IMPORT(
	ID INT NOT NULL IDENTITY(1,1),
	CREATE_DATE DATE,
	PRIMARY KEY (ID)
);

CREATE TABLE BILL(
	ID INT NOT NULL IDENTITY(1,1),
	AMOUNT INT NOT NULL,
	PRICE INT NOT NULL,
	CREATE_DATE DATE,
	PRIMARY KEY (ID)
);

CREATE TABLE PRODUCER(
	ID INT NOT NULL IDENTITY(1,1),
	NAME VARCHAR(255) NOT NULL
	PRIMARY KEY (ID)
);

CREATE TABLE TYPE_PRODUCTS(
	ID INT NOT NULL IDENTITY(1,1),
	NAME VARCHAR(255) NOT NULL
	PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS(
	ID INT NOT NULL IDENTITY(1,1),
	TYPE_PRODUCTS_ID INT NOT NULL,
	PRODUCER_ID INT NOT NULL,
	IMPORT_ID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	ORIGIN VARCHAR(255) NOT NULL,
	AMOUNT INT NOT NULL,
	PRICE INT NOT NULL,
	WARRANTY_DATE INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (TYPE_PRODUCTS_ID) REFERENCES TYPE_PRODUCTS(ID),
    FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCER(ID),
    FOREIGN KEY (IMPORT_ID) REFERENCES IMPORT(ID)
);

CREATE TABLE BILL_PRODUCTS(
	ID INT NOT NULL IDENTITY(1,1),
	BILL_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (BILL_ID) REFERENCES BILL(ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);


SELECT * FROM BILL_PRODUCTS;

DROP TABLE PRODUCTS;
DROP TABLE BILL_PRODUCTS;
DROP TABLE TYPE_PRODUCTS;
DROP TABLE PRODUCER;
DROP TABLE IMPORT;
DROP TABLE BILL;
